export const actionsInRoom = {
  ENTER: "ENTER",
  START_GAME: "START_GAME",
  SEND_PEER: "SEND_PEER",
};

export const actionsInGame = {
  MOVE_FRONT: "MOVE_FRONT",
  MOVE_BACK: "MOVE_BACK",
  MOVE_UP: "MOVE_UP",
  MOVE_DOWN: "MOVE_DOWN",
  BE_HIT: "BE_HIT",
  CAST_FIREBALL: "CAST_FIREBALL",
  CAST_LIGHTNING: "CAST_LIGHTNING",
  CAST_MINE: "CAST_MINE",
};
