export const actionsInRoom = {
  ENTER: "ENTER",
  START_GAME: "START_GAME",
  SEND_PEER: "SEND_PEER",
};

export const actionsInGame = {
  MOVE_FRONT: "MOVE_FRONT",
  MOVE_BACK: "MOVE_BACK",
  MOVE_UP: "MOVE_UP",
  MOVE_DOWN: "MOVE_DOWN",
  BE_HIT: "BE_HIT",

  CAST_FIREBALL: "CAST_FIREBALL",
  CAST_LIGHTNING: "CAST_LIGHTNING",
  LAY_MINE: "LAY_MINE",
  BUILD_TURRET: "BUILD_TURRET",
  CAST_MAGIC_WITH_TURRET: "CAST_MAGIC_WITH_TURRET",

  DRAW_STROKE: "DRAW_STROKE",
  CLEAR_STROKES: "CLEAR_STROKES",
};
